version: '3'

services:
  postgres-container:
    image: postgres
    restart: always
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ulan2001
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - gpt-anonbot_postgres-data:/var/lib/postgresql/data

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres-container
    environment:
      POSTGRES_HOST: postgres-container
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ulan2001
    volumes:
      - gpt-anonbot_postgres-data:/var/lib/postgresql/data


volumes:
  gpt-anonbot_postgres-data:
    external: true



